channels:
  # Define conda channels here.
  - conda-forge

dependencies:
  # Define conda packages here: https://anaconda.org/search
  # If available, always prefer the conda version of a package, installation will be faster and more efficient.
  - python=3.7.5
  - pip=20.1
  - pip:
      # Define pip packages here: https://pypi.org/
      - rpaframework==11.6.4 # https://rpaframework.org/releasenotes.html
